workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "TaskMaster.xcworkspace"  # Remplace par le bon nom de ton workspace si nécessaire
        XCODE_SCHEME: "TaskMaster"  # Remplace par le bon nom de ton scheme
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build the iOS app
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
          -scheme $XCODE_SCHEME \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/$XCODE_SCHEME.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
