workflows:
  web-workflow:
    name: Web App Workflow
    instance_type: mac_mini_m1
    environment:
      node: 20.11.1
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
    artifacts:
      - dist/**